platform :ios, '8.0'
inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false

# Use the local MoPub SDK for all targets.
pod 'mopub-ios-sdk', :path => '../../'

target 'MoPubSwiftSampleApp' do
  use_frameworks!
end

target 'MoPubSwiftSampleApp+CustomEvents' do
  pod 'MoPub-AdColony-Adapters'
  pod 'MoPub-AdMob-Adapters'
  pod 'MoPub-Chartboost-Adapters'
  pod 'MoPub-FacebookAudienceNetwork-Adapters'
  pod 'MoPub-Flurry-Adapters'
  pod 'MoPub-OnebyAOL-Adapters'
  pod 'MoPub-TapJoy-Adapters'
  pod 'MoPub-UnityAds-Adapters'
  pod 'MoPub-Vungle-Adapters'
end
